
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios,'16.0'
prepare_react_native_project!


target 'VerisoulReactnativeExample' do
  # Enable dynamic frameworks for VerisoulSDK xcframework support
  use_frameworks! :linkage => :dynamic
  config = use_native_modules!
  
  # VerisoulSDK from GitHub (beta versions not on CocoaPods trunk)
  pod 'VerisoulSDK', :git => 'https://github.com/verisoul/ios-sdk.git', :tag => '0.4.63-beta.6'

  use_react_native!(
    :path => config[:reactNativePath],
    :new_arch_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
